language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t kamransadique/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true kamransadique/react-test npm test

after_success:
    - docker build -t kamransadique/complex-client ./client
    - docker build -t kamransadique/complex-nginx ./nginx
    - docker build -t kamransadique/complex-server ./server
    - docker build -t kamransadique/complex-worker ./worker
    # Login to Docker CLI
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
    # Push Images to Docker
    - docker push kamransadique/complex-client
    - docker push kamransadique/complex-nginx
    - docker push kamransadique/complex-server
    - docker push kamransadique/complex-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: complex-docker
    env: ComplexDocker-env
    bucket_name: elasticbeanstalk-us-east-2-724096303363 
    bucket_path: complex-docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
